### PR TITLE
Update endgame.cpp with mate with KNQ vs K. and mate with KBQ vs K.

### PR DESCRIPTION
**Pull request by JBamro**
Mate with KNQ vs K.
needs a PushToQueenCorners table to drive the loser king in to corner with same color of queen square.

Mate with KBQ vs K.
in case the loser king was already in corner with same color of queen square, drive it easy in to this corner.

bench:1182696

### CODE REVIEW

**Comment by ianfab** [comment]
Thanks for your pull request. I will review the code later, but first a few general remarks:
- Make sure that your code compiles (fix errors/warnings).
- After compiling your code, please run the benchmark positions (`./stockfish bench`) and add the number of searched nodes as the last line of your commit message in the format `bench: 123456` (where 123456 is replaced by the actual number you got), since this information is used for tests in the continuous integration.
- Please remove spaces/tabs at the end of lines and on empty lines.

**Comment by JBamro** [comment]
sorry for errors.

**Comment by ianfab** [comment]
No problem. You can simply push changes to the branch from which you created the PR, then github will automatically update the PR as long as it is open, so you do not need to open a new one. If you need help, let me know.

**Comment by ianfab** [comment]
@JBamro Do you plan to continue the work on this PR or should I take over?

**Comment by ianfab** [comment]
@JBamro 
I have applied some changes to your PR, so feedback from your side would be welcome.

I reverted the changes to the KBQK endgame because of https://github.com/ianfab/Makruk-Stockfish/issues/4#issuecomment-370153174, and I made a few minor changes in the KNQK code. In my opinion, the code for KNQK (and KBQK) looks good now, so if there are no objections, I would commit that.

**Pull request merged**
